### ISSUE TITLE
Not possible to set new text

### ISSUE THREAD

**Issue by danielsaidi** [danielsaidi/RichTextKit#10]
After creating a rich text editor, it's not possible to completely replace the current text. Doing so currently doesn't do anything. The reason why I tag this as a feature and not a bug is that it's a known limitation in the current implementation.

This should be possible, though, so a future update should fix this.

**Comment by Nic0S** [comment]
@danielsaidi Do you know any workarounds for this? For context, we're considering using this in our chat app so the editor needs to be cleared when the user sends a message, and would like the ability to change the NSAttributedString with our own code outside of the view

**Comment by danielsaidi** [comment]
Hi @Nic0S 

I have fixed this, today actually :)

The rich text context now has functions for both setting and resetting the attributed string, which will affect the editor.

This is available in the `main` branch.
