### ISSUE TITLE
Editing string content while maintaining formatting

### ISSUE THREAD

**Issue by NateLaw86** [danielsaidi/RichTextKit#101]
Is there a way to change the content of a string and carry over the formatting?

For example, a user types in "hello **_world_**" into the editor but wherever the string "world" appears (regardless of formatting or casing) I'd like to replace with "Earth". So the desired text would look like "hello **_Earth_**" which maintains the bold and italics. I've figured out a way to replace the text but wondering if there's a way to get and apply the formatting/attributes to the new string? Perhaps I need to access the formatting file that's saved for the previous string and grab the attributes to apply to my updated string?

Thanks!

**Comment by danielsaidi** [comment]
Can you grab the formatted string and paste it in its formatted form into the string?

**Comment by NateLaw86** [comment]
I'm not sure I follow, maybe I'm just going about this the wrong way. 

My initial attempt is to use a state variable called "text" to store the original string that's typed into the editor. Then, I update the "text" variable by using the ".replacingOccurences" method on the string, but doing this loses the formatting that was applied to the original string.

So my code looks something like this:
    `@State var text: NSAttributedString`
    `text = NSAttributedString(string: text.string.replacingOccurrences(of: "world", with: "Earth"))`

Is your solution something that would be done directly in the code or just a procedure that the user would perform in the text editor?

**Comment by danielsaidi** [comment]
Oh, yes. In your code, you use `text.string` which gives you the raw string without formatting, then replace the occurrences, then create a new attributed string, which will then be based on the raw string that has no formatting.

**Comment by NateLaw86** [comment]
I see, thanks for the explanation on that. Is there an alternative method to achieve the string replacement while maintaining the original formatting then?

**Comment by danielsaidi** [comment]
I think you need to use an `NSMutableAttributedString`:

```swift
var nonMutable = NSAttributedString(string: "")
var mutable = NSMutableAttributedString(nonMutable)
b.replaceCharacters(in: <#T##NSRange#>, with: <#T##String#>)
```

**Comment by NateLaw86** [comment]
Hmm that doesn't seem to work either. I run into errors that disallow casting variables from "NSAttributedString" to "NSMutableAttributedString". Are there any other methods you are aware of that could be worth trying?
