### ISSUE TITLE
Prompt Text

### ISSUE THREAD

**Issue by noox89** [danielsaidi/RichTextKit#108]
Is there a way to set a prompt text, such as "Enter Your Note Here..." which is then removed when `text:` is not empty?

**Comment by danielsaidi** [comment]
Unfortunately, the `UI/NSTextView` views that this library wraps don't have a native placeholder.

**Comment by alelordelo** [comment]
@noox89, @danielsaidi 

Im also trying to get a placeholder to work.

I found this, but haven't managed to work yet...



https://stackoverflow.com/questions/29428594/set-the-placeholder-string-for-nstextview
```
let attributes: [NSAttributedString.Key: Any] = 
  [.foregroundColor: NSColor.secondaryLabelColor]

textView.setValue(NSAttributedString(string: placeholder, attributes: attributes), 
                  forKey: "placeholderAttributedString")
```
                  
                  
                  Instead, because NSTextView conforms to NSObject, you can just use setValue to set this property, without having to subclass:

let attributes: [NSAttributedString.Key: Any] = 
  [.foregroundColor: NSColor.secondaryLabelColor]

textView.setValue(NSAttributedString(string: placeholder, attributes: attributes), 
                  forKey: "placeholderAttributedString")

**Comment by alelordelo** [comment]
This is as fat as I got with ChatGPT....

**Add a new case to the RTKL10n enum:**

```
public enum RTKL10n: String, CaseIterable, Identifiable {
    // ... existing cases ...

    case setPlaceholder

    // ... rest of the enum ...
}
```

**Now, update the RichTextAction enum to use this new localization key:**

```
var titleKey: RTKL10n {
    switch self {
    // ... existing cases ...
    case .setPlaceholder: .setPlaceholder
    // ... rest of the switch statement ...
    }
}

```
**Make sure to add the localization string for "setPlaceholder" in your localization files (e.g., Localizable.strings) for all supported languages.** 

"setPlaceholder" = "Set Placeholder";

*Use the setPlaceholder method in your RichTextContext class as previously described:**

```
extension RichTextContext {
    func setPlaceholder(_ placeholder: String?) {
        let attributes: [NSAttributedString.Key: Any] = [
            .foregroundColor: NSColor.secondaryLabelColor,
            .font: NSFont.systemFont(ofSize: fontSize)  // Use the current fontSize
        ]
        
        let placeholderString = placeholder.map { NSAttributedString(string: $0, attributes: attributes) }
        actionPublisher.send(.setPlaceholder(placeholderString))
    }
}
```

**Comment by S1D1T1** [comment]
I implemented this for MacOS. see my comment here
https://github.com/danielsaidi/RichTextKit/discussions/165
