### ISSUE TITLE
subscribeToContextChanges is not subscribing to subscribeToShouldPasteImage and subscribeToShouldPasteImages

### ISSUE THREAD

**Issue by MarcosChevis** [danielsaidi/RichTextKit#11]
In RichTextCoordinator the subscribeToContextChanges is not calling the functions subscribeToShouldPasteImage and subscribeToShouldPasteImages.
Because of that, images are not showing on the text editor.

**Comment by danielsaidi** [comment]
Hi @MarcosChevis 

Great find, I must have missed that. 👍 

I saw your PR, thank you! I'd be happy to merge those subscription changes. However, I have some comments, so let's continue the discussion in the PR.

**Comment by danielsaidi** [comment]
This will be fixed in the next patch version.
