### ISSUE TITLE
Create RichTextEditor dynamically

### ISSUE THREAD

**Issue by xaviercamps** [danielsaidi/RichTextKit#110]
Hi!
I need to work with RichTextEdit and PKCanvasView in a same view and creating multiple view of this type with user interaction, same as Apple Notes.
User has a button to enable drawing mode and in this point, I create a new body and context. In the main view I have ForEach to know the number of contexts or body and create each RichTextEditor.
The problem appear when user tap to second RichTextEditor, Xcode print this errors:

```
=== AttributeGraph: cycle detected through attribute 289992 ===
Publishing changes from within view updates is not allowed, this will cause undefined behavior.
```

![Screenshot 2024-01-11 at 10 03 07](https://github.com/danielsaidi/RichTextKit/assets/30216506/a78dc283-e815-402f-a81b-5ff5e3c69d9c)

It's possible to work with this feature?  I attach file with a peace of this code.
[RichTextKit.txt](https://github.com/danielsaidi/RichTextKit/files/13900715/RichTextKit.txt)

**Comment by danielsaidi** [comment]
Oh, yeah now you need a separate context for each editor.

@DominikBucher12 Perhaps the editor should create its own context and provide it in a callback block? Not sure if it's possible, but it may be worth looking into. Combined with focus to set the currently active context. Hmmm.

**Comment by danielsaidi** [comment]
You can take a look at the new document-based demo app in the `main` branch for some help on how to use multiple editors.
