### ISSUE TITLE
Make build runner work with Xcode 15

### ISSUE THREAD

**Issue by danielsaidi** [danielsaidi/RichTextKit#112]
The build runner in `.github/workflows` currently fails because it can't seem to locate Xcode 15, which makes things like `#Preview` fail.

I've tried explicitly setting the Xcode version, using various marketplace variants, etc. but it still fails.

**Comment by DominikBucher12** [comment]
This is partially resolved but we do not build macOS because runner doesnt supper macOS 14 SDK and image yet...

**Comment by danielsaidi** [comment]
This works now.
