### ISSUE TITLE
Publishing changes from within view updates is not allowed, this will cause undefined behavior.

### ISSUE THREAD

**Issue by joel-meng** [danielsaidi/RichTextKit#13]
Hi @danielsaidi,
Just found several warning as below

Warning 
```Publishing changes from within view updates is not allowed, this will cause undefined behavior.```
in function ```func syncContextWithTextView() ``` in RichTextCoordinator

**Comment by joel-meng** [comment]
![image](https://user-images.githubusercontent.com/32502246/197439151-b55dfaf5-315f-4707-86f6-a0e838d78a27.png)

**Comment by danielsaidi** [comment]
Hi @joel-meng!

Oh, thanks! Something happened in Xcode 14, that causes these kind of warnings. I'll see if I can fix it in a minor update.

**Comment by danielsaidi** [comment]
@joel-meng 

I have seen this warning in some other places, where it rather seems like a bug in Xcode 14. For instance, read here:

https://www.donnywals.com/xcode-14-publishing-changes-from-within-view-updates-is-not-allowed-this-will-cause-undefined-behavior/

I will keep this around to see if Xcode 14.1 solves it.

**Comment by dominikmayer** [comment]
Hi, I can still see this in Xcode 14.1.

**Comment by danielsaidi** [comment]
Hi @dominikmayer 

Yeah, I see it too. I will have a look when I resume this project in a few weeks, but I have little hope of solving it.

**Comment by danielsaidi** [comment]
@joel-meng @dominikmayer 

I wrapped the sync logic in a `DispatchQueue.main.async` and now it seems to work. I have pushed it to the `main` branch, and will include it in the 0.2 release.

Please give it a try and see what you think.
