### ISSUE TITLE
A simple demo or documentation on how to show RichTextView  

### ISSUE THREAD

**Issue by balsimpson** [danielsaidi/RichTextKit#135]
This is a fantastic library and the documentation is excellent. Yet, as a starting SwiftUI developer, even after poring through the documentation several times, I could not figure out how to display the RichText using a `RichTextView`. Or should I be using `RichTextReader'. Any help is greatly appreciated.

**Comment by danielsaidi** [comment]
Hi @balsimpson 

Thank you! :) In SwiftUI, the `RichTextEditor` is the way to go. I will adjust the documentation a bit before the 1.0 release.

**Comment by balsimpson** [comment]
Thanks for the speedy reply. So in my Notes app I should use the RichTextEditor to display the content of all the notes? But won't that make it all editable in the List view itself?

A little more documentation on the Toolbar customisation also is highly appreciated.

**Comment by danielsaidi** [comment]
Having the editor in read-only mode should be supported.

I'll tag this with documentation todos, and hope I get around to it before 1.0.

**Comment by Guerrix** [comment]
Hello, is there a way to use `RichTextKeyboardToolbar` or similar in a `RichTextView`? Thanks

**Comment by danielsaidi** [comment]
Hi @Guerrix 

`RichTextView` is a UIKit/AppKit component, while `RichTextEditor` & `RichTextKeyboardToolbar` are built in `SwiftUI`. 

If you want to use the toolbar with the text view, you need to wrap it...but I think it'd be rather messy.

**Comment by danielsaidi** [comment]
I have added a new, more basic demo app that I hope is easier to understand. 

You can find it in the `main` branch for now.
