### ISSUE TITLE
How to set `standardRichTextFontSize`?

### ISSUE THREAD

**Issue by karlmira** [danielsaidi/RichTextKit#16]
How do I set the `standardRichTextFontSize` for my editor?
The package file itself is not editable.
```
RichTextEditor(text: $textBodyAttrib, context: context) {
	$0.setCurrentFontSize(to: 11)
}
```
is not working properly and is overwritten.

**Comment by karlmira** [comment]
OK, the fontSize can be changed 

1. by `.onAppear { context.fontSize = 11 }`
2. by button as mentioned in documentation

But.....

if text is empty, fontsize is reset to 16.

Example:

1. Open Editor with empty text: no matter, what fontsize is set, size of 16 is set (can see a short blinking)
2. Adding some text and press a button, setting fontsize to 9: everything is fine so far
3. Deleting all this text again: fontsize is reset to 16

Think, that's not a feature. :-)

**Comment by danielsaidi** [comment]
Hi @karlmira 

Yeah, there are some problems with the standard font size, where it can reset.

I will soon work with this library again, and will then check if I can improve this.

**Comment by karlmira** [comment]
Hi Daniel

> Doesn't it work to set `context.fontSize = 11` before the view appears?

Unfortunately I have to admit that I don't know how to do this because I'm relatively new to swift.

**Comment by danielsaidi** [comment]
Hey again,

I have added code to the demo to show how to do this.

**Comment by danielsaidi** [comment]
Hi again @karlmira,

I have added code to the demo to show how to do this.
