### ISSUE TITLE
Menus for Adding Text at Cursor Position

### ISSUE THREAD

**Issue by karlmira** [danielsaidi/RichTextKit#17]
As this cool RTE is OpenSource, I'd like to share a small peace of code for a nice additional feature.

Background: I have to write many letters and very often I have to add the same piece of text, that I call "snippet".
Therefor add an extra Menu (e.g. to the TopToolBar)

```
Menu {
	ForEach(snippets, id: \.self) { snippet in
		Button {
			context.pasteText(snippet.text!, at: context.selectedRange.location, moveCursorToPastedContent: true)
		} label: {
			Text(snippet.title!)
		}
	}
} label: {
	Text("insertSnippet")
}
.help("help_selectMarker")
```

Snippets here: a FetchedResults from Core Date

Have fun.

**Comment by danielsaidi** [comment]
That's great, thanks @karlmira 

I just wonder how we should best keep track of these kind of nice tips? If I close this issue, people will not be able to find it.

A new tag perhaps?

**Comment by karlmira** [comment]
Hi Daniel,

Thanks for the compliment. What about a new topic in documentation? Somewhere underneath "Quickstart". Like "Tipps & Tricks". :-)

**Comment by danielsaidi** [comment]
That's a good idea, but I think it will eventually be overwhelming with a collection utilities that use the library in different small ways.

**Comment by karlmira** [comment]
Unfortunately, I'm still a little inexperienced with github. Is it possible and not that complicated to make a new tag?

**Comment by karlmira** [comment]
> That's a good idea, but I think it will eventually be overwhelming with a collection utilities that use the library in different small ways.

On the other hand, I think, the number of hints won't be that big.

**Comment by danielsaidi** [comment]
Hi again @karlmira 

Thank you for suggesting this! I however think the use case is not common enough to motivate adding this to the library.
