### ISSUE TITLE
Unable to update binding value for RichTextKit's RichTextContext

### ISSUE THREAD

**Issue by huabin** [danielsaidi/RichTextKit#186]
Hey,

I meet an issue, it's unable to update binding value for RichTextKit's RichTextContext, here some my code

```
@State private var text = NSAttributedString(string: "")
@StateObject var context = RichTextContext()

var body: some View {
    VStack {
        RichTextEditor(text: $text, context: context) { _ in }
            .focusedValue(\.richTextContext, context)
            .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
    .onAppear {
        loadPost()
    }
}

private func loadPost() {
    let fetchedPost
    let attributedString = attributedStringFromData(fetchedPost.content)
    print("Content as AttributedString: \(attributedString)")
    text = attributedString
}
```

Output:   Content as AttributedString:  ******

But the RichTextEditor is empty. I found a solution on stackoverflow, but it seems that the link was removed.

```
https://danielsaidi.github.io/RichTextKit/documentation/richtextkit/richtextcontext/shouldsetattributedstring
```

shouldsetattributedstring has been removed.

Thank you.

**Comment by danielsaidi** [comment]
Hi @huabin 

There's a rich text action for setting the text, can you try it?

**Comment by huabin** [comment]
Hey @danielsaidi 

I will try, thank you so much.

BTW, I want to add some functions on the editor tool bar, please check this

![SD](https://github.com/danielsaidi/RichTextKit/assets/535675/272bba8f-321f-4583-bd9d-bb28ce51db2e)

Any ideas? Thank you.

**Comment by danielsaidi** [comment]
That part belongs to the main application, so I doubt you can affect it.

**Comment by huabin** [comment]
@danielsaidi 

Got it, thank you.
