### ISSUE TITLE
Editor not updating with list of files

### ISSUE THREAD

**Issue by MatthewWaller** [danielsaidi/RichTextKit#188]
Making a Notes style app.

For a List of files in ForEach and NavigationStack, I have the richtexteditor in the detail, and when I switch to different files in the sidebar of the Mac or iPad app, the editor doesn’t change. 

Is there a way, when the navigation changes to the new file, to make the editor reflect the new text?

**Comment by feixue299** [comment]
You can modify the value using the setAttributedString method in RichTextContext

**Comment by MatthewWaller** [comment]
Ah thanks.
