### ISSUE TITLE
RichTextView imageConfiguration not work when pasting image

### ISSUE THREAD

**Issue by justinjcode** [danielsaidi/RichTextKit#196]
<img width="1027" alt="image" src="https://github.com/user-attachments/assets/70ef78ca-e6cf-4be4-8bd2-ed036a135fc1">
setupSharedBehavior() called when RichTextView's frame set. 
It makes my initial imageConfiguration not work anymore.

**Comment by danielsaidi** [comment]
Hi @justinjcode 

Thank you for the detailed bug report.

I have adjusted this code to only set the image configuration if it's not manually set before. Hopefully this will fix the bug.

Commit: 7922c5d57959d13a70535a9b259236da3cdfbebc

This has been merged to `main` and will be available in `1.1`.

I'm closing this, but please test it and let me know if you still get this problem.

**Comment by justinjcode** [comment]
Hi @danielsaidi 
Thanks for your response.
I've tried commit 7922c5d, and got an error in Xcode:
package 'richtextkit' @ 7922c5d57959d13a70535a9b259236da3cdfbebc is using Swift tools version 6.0.0 but the installed version is 5.10.0 in https://github.com/danielsaidi/RichTextKit.
Please test it, thank you.

**Comment by danielsaidi** [comment]
Thank you for letting me know! 

I just released a `1.1.1`, which reverts the Swift 6 requirement. The SDK is still ready for Swift 6, but will not enforce it, to let people keep using RTK with Xcode 15.

Please let me know if you run into any other problems with the newly added concurrency-required changes.

**Comment by justinjcode** [comment]
Hi @danielsaidi 
It works perfect now!

**Comment by danielsaidi** [comment]
I'm happy to hear it! :)
