### ISSUE TITLE
[FEATURE DISCUSSION] Should we hide the vertical scroller when isScrollingEnabled is false?

### ISSUE THREAD

**Issue by travisbikkle** [danielsaidi/RichTextKit#198]
I want to thank you all for this incredible RichTextKit firstly, it saves me so much effort.

I'm writing an application to display a non-editable viewer and I get the scrollbar shown on the right:

<img width="719" alt="image" src="https://github.com/user-attachments/assets/45e1d5f3-73a5-49ec-914e-9141439618d7">

Luckily `RichTextKit` has a configuration `isScrollingEnabled` that seems to be relevant, but in the end it's for the content, not the scroller itself.

Maybe we should hide the vertical scroller when isScrollingEnabled is false? Let's discuss it...

By the way, if this proposal is approved, I will be more than happy to contribute to it, it's just one line code to achieve this:

```swift
/// RichTextEditor: line 99
public var textView: RichTextView {
        scrollView.hasVerticalScroller = config.isScrollingEnabled // add this
        return scrollView.documentView as? RichTextView ?? RichTextView()
 }
```

<img width="702" alt="image" src="https://github.com/user-attachments/assets/89da908e-f893-4cbe-bb2a-6e6bfc16b1b4">

**Comment by danielsaidi** [comment]
Hi @travisbikkle 

Sounds like a good addition! I’ll take a look 🙌
