### ISSUE TITLE
Support inserting arbitrary NSAttributedStrings

### ISSUE THREAD

**Issue by rydamckinney** [danielsaidi/RichTextKit#32]
Hey there! This is a phenomenal library. Best that I've seen by far for SwiftUI rich text w/out forcing UIKit paradigms. 
One major enhancement that would make this library even more powerful -- allowing for arbitrary `NSTextAttachments`. The functionality to support inserting `NSTextAttachments` has already been implemented internally for the `RichTextImageAttachment` capability.

An idea on implementation:
- Expose a similar method to `pasteImages` or `pasteText` that _instead_ of `[ImageRepresentable]` or `String` accepts a `NSAttributedString` (that could include an NSTextAttachment).
- Then, as it would be impossible to encode/decode arbitrary data that could be included in these inserted strings, simply ignore those values when encoding/decoding to standard file formats and leave the responsibility for encoding/decoding to the library-user
```swift
    func pasteImages(
        _ images: [ImageRepresentable],
        at index: Int,
        moveCursorToPastedContent: Bool = false
    ) {
        #if os(iOS) || os(tvOS) || os(macOS)
        guard validateImageInsertion(for: imagePasteConfiguration) else { return }
        let content = NSMutableAttributedString(attributedString: richText)
        let insertRange = NSRange(location: index, length: 0)
        let safeInsertRange = safeRange(for: insertRange)
        let insertedItems = images.count * 2   // The number of inserted "items" is the images and a newline for each
        let safeMoveIndex = safeInsertRange.location + insertedItems
        let attributes = content.richTextAttributes(at: safeInsertRange)
        let attributeRange = NSRange(location: index, length: insertedItems)
        let safeAttributeRange = safeRange(for: attributeRange)
        images.reversed().forEach {
            performPasteImage($0, at: index)
        }
        mutableRichText?.setRichTextAttributes(attributes, at: safeAttributeRange)
        if moveCursorToPastedContent {
            moveInputCursor(to: safeMoveIndex)
        }
        #else
        assertionFailure("Image pasting is not supported on this platform")
        #endif
    }
```

This would just be the first step in allowing for arbitrary subviews to be included in the RichTextEditor, but would enable a future update to support custom sub-classed NSTextAttachments like [here](https://github.com/vlas-voloshin/SubviewAttachingTextView): 

![screenshot](https://user-images.githubusercontent.com/7736588/210846865-67e4f7e4-62c2-4289-aa2f-ae47290a31a4.gif)

## References:
Some libraries that implement this type of functionality:
- https://github.com/rajdeep/proton
- https://github.com/vlas-voloshin/SubviewAttachingTextView

**Comment by danielsaidi** [comment]
Hi @rydamckinney 

Happy to hear that you like the library! :)

This is a very interesting feature suggestion. Do you think that sort of handling is needed to implement e.g. checklists as suggested here: https://github.com/danielsaidi/RichTextKit/issues/31
