### ISSUE TITLE
How to save content from the RichTextEditor?

### ISSUE THREAD

**Issue by aaronvegh** [danielsaidi/RichTextKit#34]
First off, please accept my gratitude for this lovely package! A smart, modern component to act as a rich text editor is exactly what my AppKit-based application needs right now. While I initially attempted to integrate just the view, I ultimately decided to go all-in with the SwiftUI-based `RichTextEditor` component, as a hedge to future-proof at least this part of my app. My SwiftUI-fu is a tad weak, particularly around data issues, so I'll apologize if this is a dumb question. But I note that your sample app doesn't provide a Save feature, and that's exactly what I want to be able to do at this point — I can get an NSAttributedString out of a file on disk and into the editor. I can use the editor component to edit text. But I cannot figure out how to save that text. While I have an `ObservableObject` providing the content, it doesn't appear that the attributed string property is being updated as the user works the editor; so when I save, it's the same content as was originally read off disk. Here's some code:

I'm using an `EditorContent` object from my app to contain the relevant file data:

```swift
class EditorContent: NSObject, ObservableObject {
    @Published var item: FilesystemItem
    @Published var fileURL: String
    let isReadOnly: Bool
```
The `FilesystemItem` is another `ObservableObject` that has an `text` property, which is the `NSAttributedString` content from the file on disk. This gets fed to the RichTextEditor...

```swift
editorVC = NSHostingController(rootView: EditorView(editorContent: content))
<add to view>
```
which is set out pretty much as your sample app has it:

```swift
struct EditorView: View {
    @ObservedObject var editorContent: EditorContent
    @StateObject var context = RichTextContext()

    var body: some View {
        VStack {
            RichTextEditor(text: $editorContent.item.text, context: context) {
                // You can customize the native text view here
                $0.textContentInset = CGSize(width: 40, height: 40)
            }
            .focusedValue(\.richTextContext, context)
        }
    }
}
```

I note that your sample app's actions execute from the `RichEditorContext`, but that doesn't seem to have access to the textview, or the `RichTextCoordinator`, which does. I'm kind of scratching my head trying to sort out the hierarchy, and hoping that you can set me in the right direction?

Thanks again!

**Comment by danielsaidi** [comment]
Hi @aaronvegh 

Thanks for you kind words, happy to hear that you like the package! 🙏 

Hmmm, the editor should update the attributed string binding that you provide it with. I use the library in a `DocumentGroup` based app, and they're just injecting the document's text into the editor works right away.

What happens if you display the text binding somewhere else as well, for instance in a `Text` element next to the editor?

**Comment by aaronvegh** [comment]
I managed to simply `print` the contents of the string value for that property (in its `didSet`), and as you might predict, it shows the correct content as it's typed into the RichTextEditor! That persuades me that I'm looking at the wrong part of my app for the problem here, and I'm pleased to say that RichTextKit is not my issue. Apologies for the distraction; I'll close this ticket.

**Comment by danielsaidi** [comment]
Oh, I see! Thanks for letting me know, and good luck with fixing the problem 👍
