### ISSUE TITLE
UIKit Example

### ISSUE THREAD

**Issue by Maverick1000** [danielsaidi/RichTextKit#35]
If this can be use for UIKit where is the example or do I have create the SwitfUI to UIKit bridging file?

**Comment by danielsaidi** [comment]
@Maverick1000 You can just use the `RichTextView` right away in UIKit, no SwiftUI bridge required.

**Comment by Maverick1000** [comment]
It would be great to have an example it UIKit format, that shows how to add a toolbar of options.Sent from my iPhoneOn Feb 2, 2023, at 11:41 PM, Daniel Saidi ***@***.***> wrote:﻿
@Maverick1000 You can just use the RichTextView right away in UIKit, no SwiftUI bridge required.

**Comment by danielsaidi** [comment]
I don't do any UIKit development anymore, except the bare minimum that I need to be able to do something in SwiftUI, like this case of building a rich text editor for i SwiftUI.

That the SwiftUI version works in iOS however means that the underlying tech works in UIKit, so you can use the UIKit text view like the docs says. 

I will however not put any work work into documenting UIKit and AppKit usage more than already exists in the docs. I'd be happy to merge any additions you may want to contribute with :)
