### ISSUE TITLE
On MacOS/SwiftUI how do you use keyboard to submit?

### ISSUE THREAD

**Issue by ismyhc** [danielsaidi/RichTextKit#36]
On macOS Is there a simple way to allow "enter" key to submit on RichTextEditor ? I actually couldn't find this feature on the SwiftUI TextEditor either.

I want standard text input for a chat view. Enter submits text, shift+enter adds new line.

Any insight, much appreciated!

**Comment by danielsaidi** [comment]
Hmmm not sure, SwiftUI has a native `onSubmit` view modifier, but that will (most probably) not work here. Let's keep this open and discuss it further.

**Comment by danielsaidi** [comment]
@ismyhc I have verified that you can use the SwiftUI `.onKeyPress(.return)` modifier, for instance:

```swift
RichTextEditor(
    text: $document.text,
    context: context
)
.onKeyPress(.return) {
    print("Save")
    return .handled
}
```

Keep in mind that if you do this, the text field will not insert any new lines.

Also, if you create a document-based app, you have other shortcuts for this action. See the new demo for more info.
