### ISSUE TITLE
iOS shared context between multiple RichTextEditor Instances causes Publishing change in view update warning.

### ISSUE THREAD

**Issue by jamesbradleym** [danielsaidi/RichTextKit#38]
Having multiple RichTextEditor instances with a shared context causes the xcode editor to overload with "Publishing changes from within view updates is not allowed, this will cause undefined behavior." ultimately leading to a crash.

Commenting out func textViewDidBeginEditing and func textViewDidEndEditing in the RichTextCoordinator swift file prevents this error but currently unsure of unintended consequences of this.

<img width="782" alt="Screenshot 2023-02-24 at 12 20 37 PM" src="https://user-images.githubusercontent.com/33179100/221245597-ac5b5668-155e-4a94-9dbe-0597a20a9722.png">

**Comment by danielsaidi** [comment]
Hi @jamesbradleym 

That's interesting - thanks for reporting!

Is there a special reason why you want to share the same context between two editors? A context is intended to be used with one single editor.

**Comment by jamesbradleym** [comment]
Hey @danielsaidi! Yes, I'm attempting to have multiple text editors as part of the same document for organization's sake with a global toolbar that would allow you to change text formatting options on the fly without having to reset options when you switch to a different text editor on the page.

**Comment by danielsaidi** [comment]
I'm closing this due to our mail-bound discussions. Hope things work better for you now!
