### ISSUE TITLE
rtf file Color problem

### ISSUE THREAD

**Issue by mcihanbulbul** [danielsaidi/RichTextKit#40]
I am reading attributed text from rtf file.

`try! NSAttributedString(data: data!,
                                       options: [NSAttributedString.DocumentReadingOptionKey.documentType: NSAttributedString.DocumentType.rtf],
                                  documentAttributes: nil)`
and set these text to EditorScreen

`RichTextEditor(text: $text, context: context,format: .rtf) {
            $0.textContentInset = CGSize(width: 10, height: 20)
        }`

but colors not appearing. 

If I set same text to TextView. Colors appearing

Something manipulating reader attributed text but I couldn't find

**Comment by danielsaidi** [comment]
I've had problems with the foreground color, but the background color has worked. Does it fail for both color types, or only for the foreground color?

**Comment by mcihanbulbul** [comment]
yes, foreground color is working. but text color and some fonts not working.
I added onChange to detect text changes
`.onChange(of: text, perform: { newValue in
            print(newValue)
        })`

it is triggering when opening. But I couldn't find what cause this

**Comment by mcihanbulbul** [comment]
oh finally I found in RichTextView_UIKit file in setup method , I commented out `//textColor = .label`.
finally everything is working

final method is like this

`open func setup(
        with text: NSAttributedString,
        format: RichTextDataFormat
    ) {
        attributedString = .empty
        setupInitialFontSize()
        attributedString = text
        allowsEditingTextAttributes = false
        autocapitalizationType = .sentences
        backgroundColor = .clear
        imageConfiguration = standardImageConfiguration(for: format)
        text.autosizeImageAttachments(maxSize: imageAttachmentMaxSize)
        richTextDataFormat = format
        spellCheckingType = .no
        //textColor = .label
        setContentCompressionResistancePriority(.defaultLow, for: .horizontal)
    }`

**Comment by codaman** [comment]
i created a pull request

**Comment by danielsaidi** [comment]
Thank you, I will look at it shortly!

**Comment by danielsaidi** [comment]
This works and has been released as a `0.5.2`. Thank you both so much 🙏
