### ISSUE TITLE
Catalyst support

### ISSUE THREAD

**Issue by CristianMoisei** [danielsaidi/RichTextKit#42]
Hello, I was wondering if you'd consider adding Catalyst support. Right now because of several AppKit code blocks, it's not possible to compile the project for Catalyst. I believe the issue is that the blocks in #if canImport(AppKit) will try to run in Catalyst, but some macOS classes are not available in Catalyst. An extra check for #if targetEnvironment(macCatalyst) should do the trick.

For my project I was able to use the library by adding the source code locally and removing the incompatible appkit code.

<img width="609" alt="Screenshot 2023-03-14 at 16 02 55" src="https://user-images.githubusercontent.com/7927870/225025758-e9db4202-bb3f-4e9e-b661-1687fb15ccd6.png">

**Comment by danielsaidi** [comment]
Hi @CristianMoisei 

I have not considered it, but I would love for the library to be as versatile as possible.

Does it work well when you use it on Catalyst?

**Comment by CristianMoisei** [comment]
Thanks for getting back to me. At first glance it seems to work, but I haven't been able to figure out how to use the formatting options programmatically in UIKit yet, so I will keep at it and report back if I find any issues.

**Comment by danielsaidi** [comment]
That sounds great, keep me posted! 👍

**Comment by CristianMoisei** [comment]
Hello, so it seems that the editor works in Catalyst if the #if canImport(AppKit) blocks are wrapped in a further #if targetEnvironment(macCatalyst). Exporting doesn't work and there seems to be a bug with the UITextView that causes very long strings to have some characters replaced with a quote when the user inputs something new (so this bug occurs even with a plain textview, it's not related to this library).

<img width="1024" alt="Screenshot 2023-03-14 at 18 54 32" src="https://user-images.githubusercontent.com/7927870/225085125-15207b73-4b33-4ccb-9046-4ab1c5eff4b6.png">

<img width="1024" alt="Screenshot 2023-03-14 at 19 22 46" src="https://user-images.githubusercontent.com/7927870/225087286-aee4cf85-34ce-448c-b79a-b9d2072e2045.png">

<img width="583" alt="Screenshot 2023-03-14 at 18 52 23" src="https://user-images.githubusercontent.com/7927870/225085111-8977b8f4-f9f7-41cb-847b-7f5ba81c0ac7.png">

In terms of implementing this in my UIKit app, that's not something I've been able to figure out. Would you be willing to lend me a hand as a freelancer? I can share more details privately if you have the availability.

**Comment by danielsaidi** [comment]
Hi again @CristianMoisei 

Thank you for the additional info, I will look into it shortly.

are thing, just drop me an email and we'll discuss! 👍

**Comment by danielsaidi** [comment]
@CristianMoisei 

Support for Catalyst was finally added in `0.9.3` 👍
