### ISSUE TITLE
RichTextStyleToggleGroup not showing color

### ISSUE THREAD

**Issue by DavidAlvarezDev** [danielsaidi/RichTextKit#62]
Hello again,

I noticed that the "buttonStyle" is not being applied (color now showing active color) when using the RichTextStyleToggleGroup. It's possibly due to the fact that the RichTextStyleToggleGroup uses a ControlGroup. My workaround was just to create the RichTextStyleButton myself.

Thanks in advanced,

David Alvarez
info@davidalvarezdev.com

**Comment by danielsaidi** [comment]
Hi @DavidAlvarezDev 

How do you mean? I tried these controls in the demo app and there it seemed to work.

**Comment by DavidAlvarezDev** [comment]
**Hello Daniel,**

For example, when using the premade RichTextStyleToggleGroup(), I click the "Bold" button, but the bold button does does not change colors to the default 'activeColor'. But the context is updated because the editor does start showing bold text (screen shots below in links). 

[https://photos.app.goo.gl/vKvbubfVefrNb7pn8](screenshots)


The screenshots are from a fresh project I made now in Xcode with only this code below, and of course your package imported. 

### Details on project settings and dependencies:
- Version 14.3.1 (14E300c)
- iOS target 16.4
- xCode poroject format 10.0
- RichTextKit 0.7.2


### Sample code

`//
//  ContentView.swift
//  RTE
//
//  Created by David Alvarez on 6/24/23.
//

import SwiftUI
import RichTextKit

struct ContentView: View {
    
    @State var context = RichTextContext()
    @State private var text = NSAttributedString(string: "")
    
    var body: some View {
        VStack {
            
            RichTextEditor( text: $text, context: context )
            
            RichTextKeyboardToolbar(
                context: context,
                leadingButtons: {},
                trailingButtons: {}
            )
            
        }
        .padding()
    }
}

struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        ContentView()
    }
}
`


Thanks in advanced,

David Alvarez
[info@davidalvarezdev.com](mailto:info@davidalvarezdev.com)

**Comment by danielsaidi** [comment]
Oh, I see! I will take a look at it 👍

**Comment by DominikBucher12** [comment]
Hello, this is fixed in https://github.com/danielsaidi/RichTextKit/pull/90, @danielsaidi can you please close this? :)

**Comment by alelordelo** [comment]
@DominikBucher12 

Did you get the button style to work? I tried here but could not figure out...
https://github.com/danielsaidi/RichTextKit/issues/152
