### ISSUE TITLE
Calling setAttributedString(to string: NSAttributedString) overrides font size

### ISSUE THREAD

**Issue by DavidAlvarezDev** [danielsaidi/RichTextKit#65]
Hey Daniel,

Hope your weekend is going well. I have a suggestion for this method.

Is it possible for the **string** passed to this function not be altered? Maybe I understand the usage of this function incorrectly, but I tried to use it to update my NSAttributedString to a new value after some changes to it, but I noticed the font size would change on the NSAttributedString. It was obvious why after looking at the method.

My workaround was to just set the context.shouldSetAttributedString properly directly in my method to update the editor.

Thanks,

David Alvarez
info@davidalvarezdev.com

```
   /**
     Set the attributed string to a new rich text.

     - Parameters:
       - string: The rich text string to set.
     */
    func setAttributedString(to string: NSAttributedString) {
        let mutable = NSMutableAttributedString(attributedString: string)
        mutable.setFontSize(to: fontSize)
        shouldSetAttributedString = mutable
    }
```

**Comment by danielsaidi** [comment]
Great find, I may have added the font size as a fix for a specific situation that I currently can't recall 😅 

I will take a look at this.

**Comment by minhtien1403** [comment]
@DavidAlvarezDev same problem, I have a string have multi font size, I'm use context.attributedString to get the string then I use context.setAttributedString(), the font size of text now change. Can you tell me how to fix that, thanks.
Here is my code
`func get() {
        temp = context.attributedString
    }`
`func set() {
        context.setAttributedString(to: temp)
    }`
| <img src="https://github.com/danielsaidi/RichTextKit/assets/54258059/f54b8139-979c-4004-8d8a-b1c0330f412a" width=250> | <img src="https://github.com/danielsaidi/RichTextKit/assets/54258059/c586a5b0-e0ae-4767-80bb-6adffce9b677" width=250> |

**Comment by MrGobert** [comment]
Yeah this is still happening. So when I load my saved notes that have had their font sized changed, it returns to the default size for all text.

**Comment by DominikBucher12** [comment]
hello @MrGobert, how do you load your saved notes? Or how do you mean it? Can you please share some examples? The code is long gone from the function just now, so when you call the function you will just get what attributed string you passed.

**Comment by danielsaidi** [comment]
This was due to a bug in how the rich text view setup its underlying theme. It should work in the `main` branch now.
