### ISSUE TITLE
CoreData transformer example

### ISSUE THREAD

**Issue by DavidAlvarezDev** [danielsaidi/RichTextKit#67]
Hello! Last one for today.

I was not able to get a clear answer online as to what transformer to use for the NSAttributedString be saved directly to CoreData as a Transformable property. First of all, is this a recommended approach? Any benefits to persisting the data some other way in CoreData?

It has seemed to work for me so far, but I don't know what the best approach it to persist the NSAttributedString. 

I thought it would be a common topic, but did not get a good answer. But after much investigation online, I found this code:

```
import Foundation
import UIKit
import CoreData

@objc(NSAttributedStringTransformer)
class NSAttributedStringTransformer: NSSecureUnarchiveFromDataTransformer {
    override class var allowedTopLevelClasses: [AnyClass] {
        return super.allowedTopLevelClasses + [NSAttributedString.self]
    }
}
```

Thanks in advanced for your guidance.

David Alvarez
info@davidalvarezdev.com

**EDIT:** I apologize that this issue might not be directly related to the development of your package. I just felt that getting a recommendation from this community would be a the beast approach, and that many would benefit from a post like this here, seeing that it is a very common way to persist data. I am not looking for specific code from anyone, just a thumbs up that this is a approach to persist data is a good idea.

**Comment by danielsaidi** [comment]
That's great @karlmira - thanks for sharing!

Closing this.
