### ISSUE TITLE
pod could not find 0.8.0

### ISSUE THREAD

**Issue by chinaTLJ** [danielsaidi/RichTextKit#76]
CocoaPods could not find compatible versions for pod "RichTextKit":
  In Podfile:
    RichTextKit (~> 0.8.0)
    
   my pod code is :
   pod 'RichTextKit','~> 0.8.0'

**Comment by danielsaidi** [comment]
Hi @chinaTLJ 

Thanks for notifying me - seems like I hadn't set up a pod session on my new machine.

I will however remove pod support in the future, since it has been quite unstable lately.

**Comment by chinaTLJ** [comment]
Hi, @danielsaidi ,I clone the version 0.8.0,  the bug is not be fixed:font size after pasting image,
but I fix it like  I said before.

**Comment by danielsaidi** [comment]
Strange, the font size works for me when I tap to paste the image.

I'll look at it later. ny more information you can give would be very helpful.

**Comment by chinaTLJ** [comment]
I run the demo, input text first, and then paste the picture, the cursor will automatically move to the next line, then the input text is relatively small.
So,I change the code in class   RichTextViewComponent,
func setCurrentFontSize(to size: CGFloat) {
        #if os(macOS)
        setFontSize(to: size, at: selectedRange)
        setFontSizeAtCurrentPosition(size)
        #else
        if hasSelectedRange {
            setFontSize(to: size, at: selectedRange)
        } else {//这里是设置插入图片后，在紧跟着图片后面(而非换行)的字段大小
            //源码是这句，但是插入图片后，在图片后面输入的文字大小变会成12，所以改成下面一句
//            setFontSizeAtCurrentPosition(size)
            setFontSizeAtCurrentPosition(18)//18可以，就是16不行,因为StandardFontSizeProvider里的字体大小是16，一样的就不行吗？
        }
