### ISSUE TITLE
Fontsize and Font Changes on Deleting The Whole Text

### ISSUE THREAD

**Issue by karlmira** [danielsaidi/RichTextKit#78]
I don't know if this is a bug or if I set the RTE incorrectly, but the following always happens to me:

- open a new RTE: the fontSize and fontName is set to my settings
- select all with cmd + A and delete all content
- write text: font and fontSize is different
- repeat it: again new fontSize and font
- and again, and again ...

**Comment by karlmira** [comment]
Video (.mov) for better understanding
https://www.icloud.com/iclouddrive/0faaS1Nxudo2e5N3VNakk9G4A#Bildschirmaufnahme_2023-09-06_um_16.40.05

**Comment by karlmira** [comment]
Happens on Cmd+A and Cut&Paste, too.

**Comment by danielsaidi** [comment]
Hi @karlmira 

That's strange! Thanks for letting me know.

**Comment by DominikBucher12** [comment]
Hello @karlmira, this issue should have been resolved already. If not, please bear with me until I create configuration for RichTextView in here https://github.com/DominikBucher12/RichTextKit/pull/1 and it should definitely fix your issue. 

I encountered this issue before and this was resolved with not having empty fontName... Please reply if you still have issues, I will include those fixes into the Configuration PR.

**Comment by danielsaidi** [comment]
I have merged the PR into main and it seems to work a lot better now.

I will release this as a 0.9.6.

@karlmira Can you give the new version a try once it's out?

**Comment by karlmira** [comment]
Hi Daniel,
hi Dominik

thank you very much. Great work. Problem is solved.

**Comment by danielsaidi** [comment]
🎉
