### ISSUE TITLE
How to get thumbnail of RichTextEditor

### ISSUE THREAD

**Issue by Adamekka** [danielsaidi/RichTextKit#79]
I am creating a file manager and I need to get the thumbnail of the RTF file, if I use RichTextEditor I don't know how to disable user interactions with that view

PDFDocument has .thumbnail() method, but I couldn't find that method on RichTextEditor

![image](https://github.com/danielsaidi/RichTextKit/assets/68786400/e7f7ddd6-c660-4002-ab34-8fe1709cef5f)

**Comment by e-hartig** [comment]
Sounds like you might want to use something like SwiftUI's ImageRenderer that draws a view to a bitmap. https://developer.apple.com/documentation/swiftui/imagerenderer

**Comment by Adamekka** [comment]
thanks! I'll try it

**Comment by danielsaidi** [comment]
Yeah, the ImageRenderer is great for these situations.

I'm closing this since I haven't heard anything else about it in a while. Feel free to let me know if you want to reopen it.
