### ISSUE TITLE
Keyboard toolbar modifier doesn't work

### ISSUE THREAD

**Issue by danielsaidi** [danielsaidi/RichTextKit#8]
Since RichTextKit wraps UIKit and AppKit, the SwiftUI `toolbar` view modifier with keyboard placement doesn't work.

In other words, this will not work:

```
RichTextEditor(text: $text, context: textEditorContext)
    .frame(minHeight: 200)
    .toolbar {
        ToolbarItem(placement: .keyboard) {
            Button {
                richTextContext.isBold.toggle()
            } label: {
                Image(systemName: "bold")
            }
        }
    }
```

In my own app, I developed a custom toolbar that was pinned above the keyboard. The library should offer this custom toolbar as a feature.

**Comment by jdelano** [comment]
@danielsaidi Thanks for considering this. Here's [one approach](https://medium.com/geekculture/swiftui-keyboard-toolbar-item-downsides-and-better-alternative-b673c1d53731) that I used that worked well with RichTextKit's editor.

**Comment by danielsaidi** [comment]
Yeah, this is absolutely something the library should simplify :) 

Thanks for the link - I will check it out!
