### ISSUE TITLE
Font size change when use setAttributedString()

### ISSUE THREAD

**Issue by minhtien1403** [danielsaidi/RichTextKit#84]
I have a string have multi font size, I'm use context.attributedString to get the string then I use context.setAttributedString(), the font size of text now change. Do you have any solution to keep the font size
Here is my code
func get() { temp = context.attributedString }
func set() { context.setAttributedString(to: temp) }
| <img src="https://github.com/danielsaidi/RichTextKit/assets/54258059/f54b8139-979c-4004-8d8a-b1c0330f412a" width=250> | <img src="https://github.com/danielsaidi/RichTextKit/assets/54258059/c586a5b0-e0ae-4767-80bb-6adffce9b677" width=250> |
P/s: I found that I can fix this problem by remove `mutable.setFontSize(to: fontSize)` from this function
```
func setAttributedString(to string: NSAttributedString) {
        let mutable = NSMutableAttributedString(attributedString: string)
        mutable.setFontSize(to: fontSize)
        shouldSetAttributedString = mutable
    }
```

**Comment by danielsaidi** [comment]
Hi @minhtien1403 

We have improved the font size handling in the upcoming 0.9.9. You can take a look at the `main` branch and see if it works better there.
