### ISSUE TITLE
Can we export to Word (doc or docx) file?

### ISSUE THREAD

**Issue by Stefan-UIT** [danielsaidi/RichTextKit#88]
the export pdf function is working good. There are other options like archivedData, plainText, rtf and vendorArchivedData. But I'm looking an option to export to Word (doc or docx) file, any ideas?

**Comment by danielsaidi** [comment]
I haven't found a way to export to Word yet, but if you find one I could add the menu item.

**Comment by Stefan-UIT** [comment]
i will figure it out myself, thanks so much for the quick response, I really appreciate it!

**Comment by danielsaidi** [comment]
Hope you manage to solve it! :) If you find a solution you want to share, I'd be happy to add it.
