### ISSUE TITLE
italic not work

### ISSUE THREAD

**Issue by LiLiKazine** [danielsaidi/RichTextKit#91]
_Italic_ not work both on my project and provided demo.

macOS: 14.1 (23B74)
Xcode Version 15.0.1 (15A507)

**Comment by danielsaidi** [comment]
Hi,

Hmmm I just tried the demo app on macOS Sonoma 14.1.1 and Xcode 15.0 and it works:

<img width="1085" alt="image" src="https://github.com/danielsaidi/RichTextKit/assets/429927/d632a524-ecb3-406b-82bd-ba024cc1b530">

For me, it works with both the keyboard shortcuts and the sidebar buttons.

**Comment by danielsaidi** [comment]
Hmmm seems like the "Standard" font changes to display Helvetica when a style is applied to it.

**Comment by LiLiKazine** [comment]
> Hi,
> 
> Hmmm I just tried the demo app on macOS Sonoma 14.1.1 and Xcode 15.0 and it works:
> 
> <img alt="image" width="1085" src="https://private-user-images.githubusercontent.com/429927/287718033-d632a524-ecb3-406b-82bd-ba024cc1b530.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NDUwNjgsIm5iZiI6MTcwMTc0NDc2OCwicGF0aCI6Ii80Mjk5MjcvMjg3NzE4MDMzLWQ2MzJhNTI0LWVjYjMtNDA2Yi04MmJkLWJhMDI0Y2MxYjUzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNVQwMjUyNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWI2YmM4MjI2ZGM4NDM5ZGZmZTZjMWI5NjVmOGJjYmY4NmJiNmI5NjMwNzIxZjgwMDZiODk2ZGRkYTg2NWViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oJNVMuBUstV6hbSpa82Jcx4V1k7llR3gbSgRSu3mXf8">
> For me, it works with both the keyboard shortcuts and the sidebar buttons.

It turns out to a TextKit2 issue. 
I delete all of the `layoutManager` reference in RichTextView to adopt TextKit2 features, which cause the italic trait make no effect on certain system fonts
